# This is the language of our project.
language: php

# Installs the updated version of PostgreSQL and extra APT packages.
addons:
 postgresql: "9.4"

# Ensure DB services are running.
services:
 - mysql
 - postgresql

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
# For 3.1 forward, only test PHP7.
 - 5.6
 - 7.0
 - 7.1

env:
 global:
  - MOODLE_BRANCH=MOODLE_33_STABLE
 matrix:
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-poet
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-firefox:3

install:
  #- moodle-plugin-ci add-plugin --clone https://github.com/Edudevel/emedia_questionbanks.git
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit --coverage-text
